In [7]:
import pandas as pd

data = pd.read_csv('Incendies.csv', sep=';')
data

,Année,Numéro,Département,Code INSEE,Nom de la commune,Date de première alerte,Surface parcourue (m2),Surface forêt (m2),Surface maquis garrigues (m2),Autres surfaces naturelles hors forêt (m2),...,Intervention de l'équipe RCCI,Décès ou bâtiments touchés,Nombre de décès,Nombre de bâtiments totalement détruits,Nombre de bâtiments partiellement détruits,Hygrométrie (%),Vitesse moyenne du vent (Km/h),Direction du vent,Température (°C),Précision de la donnée
0,2022,13845,06,06050,Coursegoules,2022-01-01 08:20:00,5000,NaN,5000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022,16667,04,04210,Soleilhas,2022-01-02 17:39:00,1500,1500.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022,13568,06,06074,Lantosque,2022-01-04 17:10:00,5000,1000.0,4000.0,NaN,...,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022,14942,84,84012,Beaumes-de-Venise,2022-01-05 09:38:00,5,5.0,NaN,NaN,...,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022,14358,66,66048,Cerbère,2022-01-05 10:17:00,764,NaN,764.0,NaN,...,Oui,NaN,NaN,NaN,NaN,60.0,100.0,N,9.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7062,2023,21902,83,83069,Hyères,2023-12-27 17:58:00,100,0.0,100.0,0.0,...,Non,Non,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Données partielles ou non valides
7063,2023,13754,07,07275,Saint-Mélany,2023-12-28 11:58:00,100,0.0,100.0,0.0,...,Non,Non,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
7064,2023,21903,83,83110,Rougiers,2023-12-28 17:24:00,4,0.0,4.0,0.0,...,Non,Non,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Données partielles ou non valides
7065,2023,21904,83,83036,Cavalaire-sur-Mer,2023-12-29 07:22:00,60,60.0,0.0,0.0,...,Non,Non,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Données partielles ou non valides
7066,2023,13298,34,34301,Sète,2023-12-31 03:09:00,200,0.0,200.0,0.0,...,Non,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
data['Date de première alerte'] = pd.to_datetime(data['Date de première alerte'], format='%Y-%m-%d %H:%M:%S')
data['Date de première alerte']

0      2022-01-01 08:20:00
1      2022-01-02 17:39:00
2      2022-01-04 17:10:00
3      2022-01-05 09:38:00
4      2022-01-05 10:17:00
               ...
7062   2023-12-27 17:58:00
7063   2023-12-28 11:58:00
7064   2023-12-28 17:24:00
7065   2023-12-29 07:22:00
7066   2023-12-31 03:09:00
Name: Date de première alerte, Length: 7067, dtype: datetime64[ns]

In [28]:
min_date = data['Date de première alerte'].min()
max_date = data['Date de première alerte'].max()

min_date = min_date.date()
print(min_date, max_date)

2022-01-01 2023-12-31 03:09:00